### PR TITLE
[Entity]: added Amenity model

### PR DESCRIPTION
**Pull request by annton-shakur**
Added Amenity model and ManyToMany relation with Accomodation

### CODE REVIEW

**Review by vadymhrnk — APPROVED** [review]
LGTM, only one suggestion for you to consider

**Review by TarasYurkovskyi — APPROVED** [review]
GJ!

**Review by vadymhrnk — APPROVED** [review]
Good job! Everything looks good to me

**Review by DPotapov93 — APPROVED** [review]
Great Job!

**Pull request merged**
